version: "3"
services:
  app:
    build: .
    container_name: "sia-helper"
    environment:
      - NIM=
      - PASSWORD=
      - TZ=Asia/Makassar
    volumes:
      - /path/to/data:/app/data
    ports:
      - 8080:8080
    restart: unless-stopped
