services:
  sia-helpers:
    container_name: "sia-helpers"
    image: ghcr.io/veirt/sia-helpers:latest
    build: .
    volumes:
      - ./data:/app/data
    env_file: .env
    ports:
      - 33125:33125
      - 33126:33126
    restart: unless-stopped
    depends_on:
      - login-service
  login-service:
    container_name: "sia-helpers-login-service"
    build:
      context: login-service
    env_file: .env
    ports:
      - 8000:8000
    restart: unless-stopped
