services:
  sia-helpers:
    container_name: "sia-helpers"
    image: ghcr.io/veirt/sia-helpers:latest
    build: .
    volumes:
      - ./data:/app/data
    env_file: .env
    ports:
      - 33125:33125
      - 33126:33126
    restart: unless-stopped
    depends_on:
      turnstile-solver:
        condition: service_healthy
  turnstile-solver:
    container_name: "turnstile-solver"
    environment:
      - TZ=Asia/Makassar
      - RUN_API_SOLVER=true
    build:
      context: Turnstile-Solver/Docker
    ports:
      - 5000:5000
      - 3389:3389
    restart: unless-stopped
