services:
  sia-helpers:
    container_name: "sia-helpers"
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - NIM=
      - PASSWORD=
      - TZ=Asia/Makassar
    ports: 
      - 33125:33125
    restart: unless-stopped
